algoritmo "Exercicios avaliacao"
// Função : Exercicio numero 4
// Autores : Tiago Lima
// Seção de Declarações
var
x,y,t:inteiro
s:caracter
inicio
// Seção de Comandos
s<-"s"
enquanto s="s" faca
 Escreval ("Programa que informa numeros de 1 ate numero digitado") // Escreval= escrever em linhas diferentes
  Escreval("Digite um numero")
    leia(t)
      y<-0
     para x de 1 ate t faca
        y<-y+x-1
     fimpara
     escreval("A soma dos numeros e : ",y)
    escreval (" Quer continuar? S ou N")
     Leia (s)
fimenquanto
fimalgoritmo


