algoritmo "Exercicios"
// Função : Exercicio numero 2
// Autores : Tiago Lima
// Seção de Declarações
var
numero,x,y,z: inteiro
s:caracter
inicio
// Seção de Comandos
s<-"s"
enquanto s="s" faca
 Escreval ("Programa que imprime soma de numeros ate numero declarado") // Escreval= escrever em linhas diferentes
 escreval("Digite um numero")
  leia(x)
   para numero de 1 ate x faca
      y<-numero+y
   fimpara
   escreval("   Resultado da soma",y)
      escreval (" Quer continuar? S ou N")
        Leia (s)
        y<-0
fimenquanto
fimalgoritmo
