algoritmo "Exercicio"
// Função : Exercicio numero 3
// Autor : Tiago Lima
// Seção de Declarações
var
numero,x,y:inteiro
s:caracter
inicio
// Seção de Comandos
s<-"s"
enquanto s="s" faca
Escreval ("Programa que imprime o dobro de cada numero digitado") // Escreval= escrever em linhas diferentes
   y<-x
  para numero de 1 ate 10 faca
leia(X)
  y<-x*2
 escreval("  dobro",y)
  fimpara
escreval (" Quer continuar? S ou N")
Leia (s)
fimenquanto

fimalgoritmo


