algoritmo "Exercicios avaliacao"
// Função : Exercicio numero 5
// Autores : Tiago Lima
// Seção de Declarações
var
y,z,x: real
numero:inteiro
s:caracter
inicio
// Seção de Comandos
 s<-"s"
enquanto s="s" faca
    Escreval ("Programa que faz media de 10 numeros, escreva os numeros:") // Escreval= escrever em linhas diferentes
       para numero de 1 ate 10 faca
        leia(X)
        y<-y+x
       fimpara
         z<-y/x
    escreval("Media= ",z )
    escreval (" Quer continuar? S ou N")
    Leia (s)
fimenquanto
fimalgoritmo


