algoritmo "Exercicios avaliacao"
// Função : Exemplo de Aula
// Autor : Tiago Lima
// Data : 28/05/2015
// Seção de Declarações
var
Comprimentomm,Diametromm,Comprimentopol,Diametropol: Real
inicio
// Seção de Comandos
Escreval ("Calcular polegadas para milimetros de um parafuso. ") // Escreval= escrever em linhas diferentes
Escreva ("Digite o comprimento do parafuso em milimetros: ") // Escreva = escreve na mesma linha
Leia (Comprimentomm)
Escreva ("Digite o diametro em milimetros:  ")
Leia (Diametromm)
Comprimentopol<-(25.4*Comprimentomm)/5
Diametropol <- (25.4*Diametromm)/5
Escreval ("O comprimento em polegadas e :  ", Comprimentopol, " polegadas" )
Escreval ("O diametro em polegadas e :  ", Diametropol, " polegadas" )
Escreva ("Autor TIAGO LIMA")
fimalgoritmo
