algoritmo "Exercicios avaliacao"
// Função : Exercicio numero 1
// Autores : Tiago Lima
// Seção de Declarações
var
numero,x,num: inteiro
s:caracter
inicio
// Seção de Comandos
s<-"s"
enquanto s="s" faca
  Escreval ("Programa que imprime 100 primeiros numeros pares") // Escreval= escrever em linhas diferentes
    x<-2
   para numero de 1 ate 100 faca
     Escreval ("",x)
       x<-x+2
     fimpara
     escreval (" Quer continuar? S ou N")
      Leia (s)
fimenquanto
fimalgoritmo
