algoritmo "Exercicios"
// Função : Exercicio numero 4
// Autores : Tiago Lima
// Data : 16/07/2015
// Seção de Declarações
var
val1,val2:inteiro
inicio
// Seção de Comandos
    Escreval ("Este programa imprime uma matriz ") // Escreval= escrever em linhas diferentes
    para val1 de 1 ate 5 faca
       para val2 de 1 ate 5 faca
       escreva(val1,"-",val2)
       fimpara
       escreval("")
       fimpara
Escreva ("Autor TIAGO LIMA")
fimalgoritmo
