algoritmo "Exercicios"
// Função : Exercicio numero 4
// Autores : Tiago Lima
// Data : 16/07/2015
// Seção de Declarações
var
val1:inteiro
inicio
// Seção de Comandos
    Escreval ("Este programa imprime uma matriz ") // Escreval= escrever em linhas diferentes
    para val1 de 1 ate 1 faca
       escreval(val1,"-",val1)
       fimpara
       para val1 de 2 ate 2 faca
       escreval("     ",val1,"-",val1)
       fimpara
       para val1 de 3 ate 3 faca
       escreval("          ",val1,"-",val1)
       fimpara
       para val1 de 4 ate 4 faca
       escreval("                ",val1,"-",val1)
       fimpara
       para val1 de 5 ate 5 faca
       escreval("                     ",val1,"-",val1)
       fimpara
       escreva("")

Escreva ("Autor TIAGO LIMA")
fimalgoritmo
