algoritmo "Peso ideal"
// Função :
// Autor :
// Data : 26/06/2015
// Seção de Declarações 
var
p,h:numerico
s:caracter
inicio
// Seção de Comandos 
escreval("Calcule o seu peso ideal")
escreva("Qual o seu sexo? ")
leia(s)
escreva("digite sua altura: ")
leia(h)
se(S="f")entao
p<-(62.1*h)-44.7
escreva("Seu peso ideal deve ser ",p,"kg.")
fimse
se(s="m")entao
p<-(72.7*h)-58
escreva("Seu peso ideal deve ser ",p,"kg.")
fimse
fimalgoritmo
