algoritmo "Exercicios avaliacao"
// Função : Exercicio numero 4
// Autores : Tiago Lima
// Data : 28/06/2015
// Seção de Declarações
var
senha: numerico
inicio
// Seção de Comandos
Escreval ("Programa que abre com senha. ") // Escreval= escrever em linhas diferentes
Escreva ("Digite a senha: ") // Escreva = escreve na mesma linha
Leia (senha)
 se (senha=1234)entao
 escreval ("Seja bem vindo ao Sistema Raito")
 senao
   escreval ("Voce digitou a senha errada! ")
   fimse
Escreva ("Autor TIAGO LIMA")
fimalgoritmo
