algoritmo "Exercicios avaliacao"
// Função : Exemplo de Aula
// Autores : Tiago Lima e Marceli
// Data : 28/05/2015
// Seção de Declarações
var
perimetro,area,diagonal,base,altura: NUMERICO
inicio
// Seção de Comandos


Escreva ("Digite o valor da base: ") // Escreva = escreve na mesma linha
Leia (base)
Escreva ("Digite o valor da altura: ") // Escreva = escreve na mesma linha
Leia (altura)
perimetro<-(base*2)+(altura*2)
area<-base*altura
diagonal<-  RAIZQ((base*base)+(altura*altura))
Escreval ("O perimetro e :  ", perimetro   )
Escreval ("A altura e:  ", altura   )
Escreval ("A area e:  ", diagonal   )
Escreva ("Autor TIAGO LIMA e Marceli")
fimalgoritmo
