algoritmo "Exercicios avaliacao"
// Função : Exemplo de Aula
// Autores : Tiago Lima e Marceli
// Data : 28/05/2015
// Seção de Declarações
var
a,b,c,d,n,den: numerico
inicio
// Seção de Comandos
Escreval ("Calcular formula do professor Erivelton. ") // Escreval= escrever em linhas diferentes
Escreva ("Digite valor de a: ") // Escreva = escreve na mesma linha
Leia (a)
Escreva ("Digite valor de b: ") // Escreva = escreve na mesma linha
Leia (b)
Escreva ("Digite valor de c: ") // Escreva = escreve na mesma linha
Leia (c)
Escreva ("Digite valor de d: ") // Escreva = escreve na mesma linha
Leia (d)
n<-(a*d)+(b*c)
den<-(b*d)
Escreval ("O valor do numerador e :  ", n, " numerador" )
Escreval ("O valor do denominador e :  ", den, " denominador" )
Escreva ("Autor TIAGO LIMA e Marceli")
fimalgoritmo
