algoritmo "Exercicios avaliacao"
// Função : Exercicio numero 4
// Autores : Tiago Lima
// Data : 28/06/2015
// Seção de Declarações
var
numero,x: inteiro
s:caracter
inicio
// Seção de Comandos
s<-"s"
enquanto s="s" faca
Escreval ("Programa com estrutura de repeticao") // Escreval= escrever em linhas diferentes
Escreval ("Informe a quantidade repeticoes")
leia(x) // Escreval= escrever em linhas diferentes // Escreva = escreve na mesma linha
 se (x >0)e (x<=30) entao
 para numero de 1 ate x faca
Escreval ("Adoro a Disciplina Logica de Programacao")
fimpara
senao
 escreval("Valor Invalido")
 fimse
escreval (" Quer continuar? S ou N")
Leia (s)
fimenquanto

fimalgoritmo

