algoritmo "Exercicios avaliacao"
// Função : Exercicio numero 4
// Autores : Tiago Lima
// Data : 28/06/2015
// Seção de Declarações
var
numero: inteiro
inicio
// Seção de Comandos
Escreval ("Programa com estrutura de repeticao") // Escreval= escrever em linhas diferentes
 // Escreva = escreve na mesma linha
 para numero de 1 ate 10 faca
Escreval ("Autor TIAGO LIMA")
fimpara
fimalgoritmo
