algoritmo "Exercicios avaliacao"
// Função : Exercicio numero 4
// Autores : Tiago Lima
// Data : 28/06/2015
// Seção de Declarações
var
numero,x,num: inteiro
s:caracter
inicio
// Seção de Comandos
s<-"s"
enquanto s="s" faca
Escreval ("Programa que imprime numeros em ordem decrescente") // Escreval= escrever em linhas diferentes
Escreval ("Informe o maior numero)")
leia(x) // Escreval= escrever em linhas diferentes // Escreva = escreve na mesma linha

  para numero de 1 ate x faca
Escreval (" ",x)
x<-x-1

fimpara
escreval (" Quer continuar? S ou N")
Leia (s)
fimenquanto

fimalgoritmo

