algoritmo "Exercicios avaliacao"
// Função : Exercicio numero 4
// Autores : Tiago Lima
// Data : 28/06/2015
// Seção de Declarações
var
y,z: real
numero,x:inteiro
s:caracter
inicio
// Seção de Comandos
s<-"s"
enquanto s="s" faca
Escreval ("Programa que informa se numero e positivo ou negativo") // Escreval= escrever em linhas diferentes
  para numero de 1 ate 10 faca
leia(X)
 se (x=0) entao
 escreval("  neutro")
 fimse
 se(x>0) entao
  escreval ("positivo")
  fimse
 se (x<0) entao
 escreval("  negativo")
  fimse
fimpara

escreval (" Quer continuar? S ou N")
Leia (s)
fimenquanto

fimalgoritmo


