algoritmo "Exercicios avaliacao"
// Função : Exemplo de Aula
// Autores : Tiago Lima e Marceli
// Data : 28/05/2015
// Seção de Declarações
var
Numero1,Numero2,Soma: NUMERICO
inicio
// Seção de Comandos


Escreva ("Digite o numero1: ") // Escreva = escreve na mesma linha
Leia (Numero1)
Escreva ("Digite o numero2: ") // Escreva = escreve na mesma linha
Leia (Numero2)
Soma<-Numero1+Numero2
Escreval ("Soma =  ", Soma   )

Escreva ("Autor TIAGO LIMA e Marceli")
fimalgoritmo
