algoritmo "Exercicios avaliacao"
// Função : Exemplo de Aula
// Autores : Tiago Lima e Marceli
// Data : 28/05/2015
// Seção de Declarações
var
saldo,aplicacao: NUMERICO
inicio
// Seção de Comandos


Escreva ("Digite o saldo: ") // Escreva = escreve na mesma linha
Leia (saldo)
aplicacao<-saldo+(saldo*0.08) // aplicacao de 8 porcento
Escreval ("A aplicacao e:  ", aplicacao   )
Escreva ("Autor TIAGO LIMA e Marceli")
fimalgoritmo
