algoritmo "Exercicios avaliacao"
// Função : Exemplo de Aula
// Autores : Tiago Lima e Marceli
// Data : 28/05/2015
// Seção de Declarações
var
Numero,Antecessor,Sucessor: NUMERICO
inicio
// Seção de Comandos


Escreva ("Digite o numero: ") // Escreva = escreve na mesma linha
Leia (Numero)
Antecessor<- Numero-1
Sucessor<-Numero+1
Escreval ("O antecessor e :  ", Antecessor, " NUM" )
Escreval ("O sucessor e :  ", Sucessor, " NUM" )
Escreva ("Autor TIAGO LIMA e Marceli")
fimalgoritmo
