algoritmo "Exercicios avaliacao"
// Função : Exemplo de Aula
// Autores : Tiago Lima e Marceli
// Data : 28/05/2015
// Seção de Declarações
var
Numero,TercaParte: NUMERICO
inicio
// Seção de Comandos


Escreva ("Digite o numero: ") // Escreva = escreve na mesma linha
Leia (Numero)
TercaParte<-Numero/3
Escreval ("A terca parte do numero e:  ", TercaParte   )

Escreva ("Autor TIAGO LIMA e Marceli")
fimalgoritmo
